"""Gate thresholds — derived from CenterDistill paper training statistics.

τ_conf  = 0.44  — 75th percentile of max P_T
τ_multi = 0.24  — 60th percentile of second mass among non-ANSWER
τ_ent   = 1.51  — median entropy of non-ANSWER, in NATS (np.log, NEVER log2)

All six hyperparameters in the paper are derived programmatically from training
statistics — no grid search. Domain-specific overrides are generated by
scripts/derive_thresholds.py and stored in config/thresholds.<domain>.json.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any


@dataclass(frozen=True)
class GateThresholds:
    """Threshold configuration for ambiguity gate routing.

    Evaluation order is fixed and MUST NOT be reordered (AGENTS.md rule 2):
        1. max_prob > tau_conf        → ANSWER
        2. second_mass > tau_multi    → ALTERNATIVES
        3. entropy > tau_ent          → CLARIFY
        4. else                       → ANSWER (conservative default)

    Reordering changes results silently — there is no error, just wrong routing.
    """

    tau_conf: float = 0.44
    """Confidence threshold. 75th percentile of max P_T."""

    tau_multi: float = 0.24
    """Multi-interpretation threshold. 60th percentile of second mass among non-ANSWER."""

    tau_ent: float = 1.51
    """Entropy threshold in NATS (natural log). Median entropy of non-ANSWER.

    CRITICAL: this is in nats (np.log). Using log2 produces a value off by
    a factor of ln(2) ≈ 0.693, which silently misroutes queries with no
    error anywhere in the pipeline. There is a contract test for this —
    do not delete it (tests/test_entropy_units.py).
    """

    def as_dict(self) -> dict[str, float]:
        """Return thresholds as a dict for inclusion in GateDecision."""
        return {
            "tau_conf": self.tau_conf,
            "tau_multi": self.tau_multi,
            "tau_ent": self.tau_ent,
        }


# Paper defaults — do not modify without re-running scripts/derive_thresholds.py
DEFAULT_THRESHOLDS = GateThresholds()


def get_thresholds_from_settings(settings: Any = None) -> GateThresholds:
    """Load thresholds from Settings/env or fallback to DEFAULT_THRESHOLDS."""
    if settings is None:
        from app.settings import get_settings

        settings = get_settings()

    def _val(attr: str, default: float) -> float:
        v = getattr(settings, attr, None)
        return float(v) if v is not None else default

    tau_conf = _val("tau_conf", DEFAULT_THRESHOLDS.tau_conf)
    tau_multi = _val("tau_multi", DEFAULT_THRESHOLDS.tau_multi)
    tau_ent = _val("tau_ent", DEFAULT_THRESHOLDS.tau_ent)

    return GateThresholds(
        tau_conf=float(tau_conf),
        tau_multi=float(tau_multi),
        tau_ent=float(tau_ent),
    )
